// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TheChg.Infrastructure.Organization;

#nullable disable

namespace TheChg.Infrastructure.Organization.Migrations
{
    [DbContext(typeof(OrganizationDbContext))]
    [Migration("20260916165337_InitialOrganization")]
    partial class InitialOrganization
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TheChg.Domain.Organization.Church", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Churches", "organization");
                });

            modelBuilder.Entity("TheChg.Domain.Organization.OrganizationUnit", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ChurchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UnitType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChurchId", "Code")
                        .IsUnique()
                        .HasFilter("[UnitType] = 1");

                    b.HasIndex("ChurchId", "ParentId", "Code")
                        .IsUnique();

                    b.ToTable("OrganizationalUnits", "organization", t =>
                        {
                            t.HasCheckConstraint("CK_OrganizationalUnit_ParentShape", "([UnitType] = 1 AND [ParentId] IS NULL) OR ([UnitType] IN (2, 3) AND [ParentId] IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("TheChg.Domain.Organization.OrganizationUnit", b =>
                {
                    b.HasOne("TheChg.Domain.Organization.Church", null)
                        .WithMany()
                        .HasForeignKey("ChurchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TheChg.Domain.Organization.OrganizationUnit", null)
                        .WithMany()
                        .HasForeignKey("ChurchId", "ParentId")
                        .HasPrincipalKey("ChurchId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
